### ISSUE TITLE
Problem with installing netifaces on MacOS

### ISSUE THREAD

**Issue by nkongsuwan** [ioflo/hio#26]
I have a problem installing netifaces 0.11.0 on MacOS. This problem is solved when I changed to netifaces2 0.0.16 (https://pypi.org/project/netifaces2/).

**Comment by SmithSamuelM** [comment]
good to know I will try out netifaces2 and if it looks good change the requirement for Hio

**Comment by SmithSamuelM** [comment]
removed dependencies on netificaces
