### ISSUE TITLE
Are blake3 and pysodium dependencies used?

### ISSUE THREAD

**Issue by lenkan** [ioflo/hio#31]
I could not find any reference to them in the codebase, so just wondering if they are still needed in this project? The blake3 dependency specifically makes it a little bit more cumbersome to use.

**Comment by SmithSamuelM** [comment]
Given this is a python project Not sure why Blake3 is more cumbersome than libsodium.  The original intent was that Hio would have a relaible UDP message protocol support, but that may move to its own repo as it now will likely use CESR. So the dependencies on libsodium and blake3 may be stale and could be removed.

**Comment by lenkan** [comment]
> Given this is a python project Not sure why Blake3 is more cumbersome than libsodium.

The blake3 dependency install was the one that failed first when I was trying to build a docker image with this library. It seemed to require me to set up rust first.

**Comment by SmithSamuelM** [comment]
fixed in hio 0.6.10 see https://github.com/ioflo/hio/pull/32
